### ISSUE TITLE
Calculator Bugs

### ISSUE THREAD

**Issue by mdavis1982** [mdavis1982/eve#30]
There are a few little issues with the `calc` command:
1. `@eve calc sqrt(-1)` gives `sqrt(-1) _evaluates to_ *NAN*`

We should probably check for `NAN` in the result and give a proper error.
1. ~~`@eve calc 10e+5 * 1` gives `10e+5 * 1 _evaluates to_ *32.18281828459*`~~

~~There's nothing wrong with the answer - it's correct - but the formatting of the `*` makes it look as though it has parts in bold.~~
1. `@eve calc 0 ^ 0` gives a division by zero error

**Comment by Dylan-DPC-zz** [comment]
Eve calculates 0 \* log(0) wrongly 

@eve calculate 0 \* log(0)
eveBOT [3:20 PM]  :  `0 * log(0) = 0`

Expected Answer: NaN

**Comment by byCedric** [comment]
Maybe we could try some other library to fix those strange issues with `sqrt(-1)` and `0 ^ 0`? I wil try something later this evening! (see [this](https://github.com/mdavis1982/eve/issues/22#issuecomment-253621111) for all libraries I found)

**Comment by byCedric** [comment]
Another update here on the bug hunting. I would like to thank you all for breaking our creation within 60 seconds. ;) 

Currently the Mossadal library has been implemented, but apparently this does not satisfy the Larachat's community's needs. Therefor I tried the following edge cases on multiple libraries that I found earlier. Here are the results:

| edge case | _expected_ | Mossadal | Hoa | NXP |
| --- | --- | --- | --- | --- |
| `@eve calculate 0 ^ 0` | _**1**_ | _division by zero exception_ | _**1**_ | _unidentified offset exception_ |
| `@eve calculate sqrt(-1)` | [_**i**_](https://en.wikipedia.org/wiki/Imaginary_unit) | _NAN_ | _NAN_ | _unknown function exception_ |
| `@eve calculate log(0)` | _**-INF**_ | _**-INF**_ | _**-INF**_ | _unknown function exception_ |
| `@eve calculate 0 * log(0)` | _**NAN**_ | 0 | _**NAN**_ | _unknown function exception_ |

> Hoa does not support the `^` sign, instead it uses a `pow(a,b)` syntax.

As you can see, the winner is [Hoa](https://github.com/hoaproject/math). I'm not a fan of this library since it's really big and partially written with Pascal. Also it does NOT support the `^` sign. However they were not wrong with [`i`](https://en.wikipedia.org/wiki/Imaginary_unit) being a `NAN`, since its imaginary, thus achieving a 100% score of the edge cases.

Maybe it's better to try to solve it with Mossadal. If this fails, pass it on to something like Google and see if they can solve it. What do you guys think about this?

**Comment by mdavis1982** [comment]
@byCedric Thanks for all of your work on this.

If we could solve it with Mossadal then that would probably be my preferred option. I don't think it's scalable to pass over the query to Google or somewhere else if it fails.

How does that sit with you?

**Comment by byCedric** [comment]
No problem at all! If we want to solve it, using only the library we have to find a better one or help fix the bugs at the library's [repo](https://github.com/mossadal/math-parser/issues). I'm also a fan of the library only solution since Eve is something bigger than calculating only ;). I'm going to file the bugs there anyways, feel free to chip in!

**Comment by byCedric** [comment]
Mossadal has spoken! The mathematician himself would not like to change the behaviour of `0 ^ 0` but we can extend the interpreter ourselfs. So do we want this to return `1`? As for the other `0 * log(0)`, it's reported as bug and will be resolved!

**Comment by byCedric** [comment]
The pull request fixes the unexpected outcome of `0 ^ 0 = 1` and `0 * log(0) = NAN`!
